name: my-environment
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - plotly
  - pandas
  - matplotlib
  - scikitlearn
  - r-base=4.0
  - r-dpylyr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - r-stringr
  - r-plotly
